VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.box = "precise32"

config.vm.define :web do |web_config|
   web_config.vm.network :private_network, :ip => "192.168.33.12"
   web_config.vm.provision "puppet" do |puppet|
   puppet.module_path = "modules"
   puppet.manifest_file = "web.pp"
   end
end

end
